[package]
name = "grokdb"
version = "0.1.0"
authors = ["Alberto Leal <mail4alberto@gmail.com>"]

license = "MIT"

[dependencies.clap]
version = "1.4"

[dependencies.chrono]
version = "0.2"

[dependencies.rusqlite]
git = "https://github.com/Dashed/rusqlite"
rev = "7c565c636cee831643c3d3f9395ba49f4324771a"

[dependencies.iron]
version = "0.2"

# iron plugins
[dependencies.staticfile]
version = "0"

[dependencies.logger]
version = "0"

[dependencies.router]
version = "0"
