[package]
name = "grokdb"
version = "0.1.0"
authors = ["Alberto Leal <mail4alberto@gmail.com>"]

license = "MIT"


[dependencies.clap]
version = "1.4"

[dependencies.chrono]
version = "0.2"

[dependencies.rusqlite]
git = "https://github.com/Dashed/rusqlite"
rev = "babbb29757bcf512b90385dcce8397585650cae8"
features = ["named_params"]

[dependencies.iron]
version = "0.2"

# iron plugins
[dependencies.staticfile]
version = "0"

[dependencies.logger]
version = "0"

[dependencies.router]
version = "0"

[dependencies.bodyparser]
version = "0"

[dependencies.rustc-serialize]
version = "0.3"

